/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author pc
 */
public class QuestionShower extends javax.swing.JFrame {
ResultSet rs;
Connection conn;
 Statement st;
int  counter=1;
    private static QuestionShower getinstance() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    /**
     * Creates new form QuestionShower
     */
    public QuestionShower() {

        initComponents();
        getContentPane().setBackground(Color.pink);
        
       
       new Thread()
        {            
           int minutes=2;
            public void run()
            {
                int  seconds = 60;
                --minutes;
       final int timerun=0;
        while (true)
        {
            try {
               Thread.sleep(1000);
               seconds--;
	if(seconds == 0){
                    seconds += 59;
                    minutes--;
				}
				l6.setText(+minutes+" mins : "+seconds+" secs ");
               
                if(seconds==timerun){
                   QuestionShower obj = QuestionShower.getinstance();
                        obj.dispose();
                			
                }
		    }
            catch(InterruptedException ex)
            {
                System.out.print(ex);
            } 
            }
            }
        }.start();
        try
      
        {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            String url = "jdbc:ucanaccess://C:\\Users\\pc\\Documents\\NetBeansProjects\\FinalProjectJava2354\\Database.accdb";
            conn = DriverManager.getConnection(url);
            st = conn.createStatement();
         
                    String q = "Select *From Question";
                    rs = st.executeQuery(q);
                      if(rs!=null && rs.next())
                     {
                         question.setText(rs.getString("QuestionDesciption"));
                         l1.setText(rs.getString("FirstOption"));
                         l2.setText(rs.getString("SecondOption"));
                         l3.setText(rs.getString("ThirdOption"));
                         l4.setText(rs.getString("FourthOption"));
                         r1.setSelected(false);
                         r1.setSelected(false);
                         r1.setSelected(false);
                         r1.setSelected(false);
                      
                         
                     }
                  
            
            }
            catch(Exception e)
            {
                
                JOptionPane.showMessageDialog(null,"Please Select a Choice");
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        question = new javax.swing.JTextArea();
        submit = new javax.swing.JButton();
        next = new javax.swing.JButton();
        l6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        qno = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        r1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });

        r2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });

        r3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });

        r4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4ActionPerformed(evt);
            }
        });

        question.setColumns(20);
        question.setFont(new java.awt.Font("RubyScriptBroad", 1, 14)); // NOI18N
        question.setRows(5);
        jScrollPane1.setViewportView(question);

        submit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        next.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        next.setText("Skip Question");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        l6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Decorated035 BT", 1, 24)); // NOI18N
        jLabel1.setText("Question");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Done Test");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(r4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(submit)
                                .addGap(137, 137, 137)
                                .addComponent(next)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addComponent(l4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(r3)
                        .addGap(18, 18, 18)
                        .addComponent(l3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(r2)
                        .addGap(18, 18, 18)
                        .addComponent(l2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(r1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qno)
                                .addGap(50, 50, 50)
                                .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1))))
                .addContainerGap(587, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(qno)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r1)
                    .addComponent(l1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r2)
                    .addComponent(l2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r3)
                    .addComponent(l3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r4)
                    .addComponent(l4))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(next)
                    .addComponent(jButton1))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
                counter++;
        String c= String.valueOf(counter);
         jLabel2.setText(c);
try
        {
            rs.next();
            question.setText(rs.getString("QuestionDesciption"));

            l1.setText(rs.getString("FirstOption"));
            l2.setText(rs.getString("SecondOption"));
            l3.setText(rs.getString("ThirdOption"));
            l4.setText(rs.getString("FourthOption"));
            
        r1.setSelected(false);
        r2.setSelected(false);
        r3.setSelected(false);
        r4.setSelected(false);

        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Your Test is Done");
     
        }
        if(r1.isSelected())
        {
            try
            {

                String url = "jdbc:ucanaccess://C:\\Users\\pc\\Documents\\NetBeansProjects\\FinalProjectJava2354\\Database.accdb";
                conn=DriverManager.getConnection(url);
                String sql= "INSERT INTO Completed_test(Can_Ans)"+"Values ('"+l1.getText()+"')";
                st = conn.createStatement();
                rs=st.executeQuery(sql);
                r1.setSelected(false);
                r1.setSelected(false);
                r1.setSelected(false);
                r1.setSelected(false);
            }

            catch(Exception e)
            {
             
            }
        }
        else if(r2.isSelected())
        {
            try
            {

                String url = "jdbc:ucanaccess://C:\\Users\\pc\\Documents\\NetBeansProjects\\FinalProjectJava2354\\Database.accdb";
                conn=DriverManager.getConnection(url);
                String sql= "INSERT INTO Completed_test(Can_Ans)"+"Values ('"+l2.getText()+"')";
                
                Statement st = conn.createStatement();
                ResultSet rs=st.executeQuery(sql);
                st.executeQuery(sql);
                r1.setSelected(false);
                r1.setSelected(false);
                r1.setSelected(false);
                r1.setSelected(false);
            }

            catch(Exception e)
            {
               
            }
        }
        else if(r3.isSelected())
        {
            try
            {

                String url = "jdbc:ucanaccess://C:\\Users\\pc\\Documents\\NetBeansProjects\\FinalProjectJava2354\\Database.accdb";
                conn=DriverManager.getConnection(url);
                String sql= "INSERT INTO Completed_test(Can_Ans)"+"Values ('"+l3.getText()+"')";
                Statement st = conn.createStatement();
                st.executeQuery(sql);
            }

            catch(Exception e)
            {
             
            }
        }
        else if (r4.isSelected())
        {
            try
            {
                
                String url = "jdbc:ucanaccess://C:\\Users\\pc\\Documents\\NetBeansProjects\\FinalProjectJava2354\\Database.accdb";
                conn=DriverManager.getConnection(url);
                String sql= "INSERT INTO Completed_test(Can_Ans)"+"Values ('"+l4.getText()+"')";
                Statement st = conn.createStatement();
                st.executeQuery(sql);
                r1.setSelected(false);
                r2.setSelected(false);
                r3.setSelected(false);
                r4.setSelected(false);
            }

            catch(Exception e)
            {
             
            }
        }


    }//GEN-LAST:event_submitActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        counter++;
        String c=String.valueOf(counter);
        jLabel2.setText(c);
        try
        {
            rs.next();
            question.setText(rs.getString("QuestionDesciption"));
            l1.setText(rs.getString("FirstOption"));
            l2.setText(rs.getString("SecondOption"));
            l3.setText(rs.getString("ThirdOption"));
            l4.setText(rs.getString("FourthOption"));

        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Test finished");
     
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_nextActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        r2.setSelected(false);
        r3.setSelected(false);
        r4.setSelected(false);


        // TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        r1.setSelected(false);
        r3.setSelected(false);
        r4.setSelected(false);


        // TODO add your handling code here:
    }//GEN-LAST:event_r2ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        r2.setSelected(false);
        r1.setSelected(false);
        r4.setSelected(false);


        // TODO add your handling code here:
    }//GEN-LAST:event_r3ActionPerformed

    private void r4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4ActionPerformed
        r2.setSelected(false);
        r3.setSelected(false);
        r1.setSelected(false);


        // TODO add your handling code here:
    }//GEN-LAST:event_r4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionShower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionShower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionShower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionShower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuestionShower().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l6;
    private javax.swing.JButton next;
    private javax.swing.JLabel qno;
    private javax.swing.JTextArea question;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
